# Generated by Django 5.2 on 2025-04-16 08:29

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='core.category')),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'community',
                'verbose_name_plural': 'communities',
                'db_table': 'communities',
            },
        ),
    ]
