# Generated by Django 5.2 on 2025-04-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
