# Generated by Django 5.2 on 2025-04-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='followers',
        ),
    ]
