# Generated by Django 5.2 on 2025-04-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_community_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='followers',
        ),
    ]
