# Generated by Django 5.2 on 2025-04-19 14:52

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_search_vector_topic_topics_search__066084_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
