# Generated by Django 5.2 on 2025-05-07 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_topicview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='views',
        ),
    ]
