# Generated by Django 5.2 on 2025-05-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_remove_topic_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicView',
        ),
    ]
