# Generated by Django 5.2 on 2025-05-08 23:56

import file_validator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_delete_topicview'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[file_validator.models.DjangoFileValidator(acceptable_mimes=['image/jpeg', 'image/png', 'image/webp'], acceptable_types=['image'], libraries=['filetype', 'mimetypes'], max_upload_file_size=5242880)]),
        ),
    ]
