# Generated by Django 5.2 on 2025-05-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0010_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
