# Generated by Django 5.2 on 2025-05-07 20:14

import autoslug.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django_extensions.db.fields
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0009_delete_topicview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=64)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=150, null=True, populate_from='comment_id')),
                ('content', tinymce.models.HTMLField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='topics.topic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comments',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='comments_search__0ffa0a_gin')],
            },
        ),
    ]
