# Generated by Django 5.2 on 2025-04-17 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_unique_together_and_more'),
        ('core', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='following_communities',
            field=models.ManyToManyField(blank=True, related_name='followed_communities', to='core.community'),
        ),
    ]
