# Generated by Django 5.2 on 2025-04-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_deleteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_link',
            field=models.URLField(blank=True, default='', max_length=350),
        ),
        migrations.AddField(
            model_name='customuser',
            name='newsletter_link',
            field=models.URLField(blank=True, default='', max_length=350),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website_link',
            field=models.URLField(blank=True, default='', max_length=350),
        ),
        migrations.AddField(
            model_name='customuser',
            name='x_link',
            field=models.URLField(blank=True, default='', max_length=350),
        ),
        migrations.AddField(
            model_name='customuser',
            name='yt_link',
            field=models.URLField(blank=True, default='', max_length=350),
        ),
    ]
