# Generated by Django 5.2 on 2025-04-20 13:22

import autoslug.fields
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=64)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='search_id')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saved search',
                'verbose_name_plural': 'saved searches',
                'db_table': 'saved_searches',
            },
        ),
    ]
