# Generated by Django 5.2 on 2025-04-25 08:41

import autoslug.fields
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_history_id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=64)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='search_history_id')),
                ('query', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('search_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'search history',
                'verbose_name_plural': 'search history',
                'db_table': 'search_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
