# Generated by Django 5.2 on 2025-04-25 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_searchhistory_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together={('user', 'query')},
        ),
    ]
