# Generated by Django 5.2 on 2025-05-09 22:04

import autoslug.fields
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_category_followers'),
        ('search', '0004_alter_searchhistory_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCommunityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_community_history_id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=64)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='search_community_history_id')),
                ('query', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to='core.community')),
            ],
            options={
                'verbose_name': 'Search Community History',
                'verbose_name_plural': 'Search Community Histories',
                'ordering': ['-created'],
                'unique_together': {('community', 'query')},
            },
        ),
    ]
